@url = http://localhost:8000
###
GET {{url}}/

###
GET {{url}}/get/5ec3f5f849ba7b7d22a3ef01

###
POST {{url}}/add HTTP/1.1
Content-Type: application/json

{
    "code":"BTL1",
    "unit_cost":100.00,
    "description":"fridge bottle"
}