// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"billme/api/inventory"
)

// Injectors from wire.go:

func InitInventoryAPI() inventory.API {
	repo := inventory.ProvideInventoryRepo()
	service := inventory.ProvideInventoryService(repo)
	api := inventory.ProvideInventoryAPI(service)
	return api
}
